version: '3.9'

services:

  db:
    image: postgres:17-alpine
    restart: always
    container_name: TM_postgres
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  app:
    build:
      context: ./
      dockerfile: ./deploy/prod/Dockerfile
    restart: always
    container_name: TM_app
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db


volumes:
  db:
  app: